version: 2.1
general:
  filters:
    branches:
      only:
        - /hattrick_branch/
jobs:
  build:
    docker:
      - image: cirrusci/flutter:1.22.6
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk